### ISSUE TITLE
[$20] PUT call never returns when timelineTemplateId is missing

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-api#202]
Following call never returns because server faced unhandled promise rejection.
```
curl 'https://api.topcoder-dev.com/v5/challenges/8e1be511-ce4d-4425-8601-04387550aadf' \
  -X 'PUT' \
  -H 'authority: api.topcoder-dev.com' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'authorization: Bearer <JWT_TOKEN>' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36' \
  -H 'content-type: application/json' \
  -H 'origin: http://local.topcoder-dev.com:3000' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: http://local.topcoder-dev.com:3000/projects/16573/challenges/8e1be511-ce4d-4425-8601-04387550aadf/edit' \
  -H 'accept-language: en-US,en;q=0.9' \
  --data-binary '{"phases":[{"duration":172800,"phaseId":"fb21431c-119e-4bc7-b447-d0af3f2be6b4"},{"duration":21600,"phaseId":"2752454b-0952-4a42-a4f0-f3fb88a9b065"},{"duration":518400,"phaseId":"a93544bc-c165-4af4-b55e-18f3593b457a"},{"duration":518400,"phaseId":"6950164f-3c5e-4bdc-abc8-22aaf5a1bd49"},{"duration":14400,"phaseId":"2d7d3d85-0b29-4989-b3b4-be7f2b1d0aa6"},{"duration":518400,"phaseId":"aa5a3f78-79e0-4bf7-93ff-b11e8f5b398b"},{"duration":432000,"phaseId":"ad985cff-ad3e-44de-b54e-3992505ba0ae"}],"typeId":"aea77c1c-1b38-4942-bdb2-937180532dcb","name":"Testing Design CHallenge","description":"<p>Testing design challenge</p><br />Please read above","tags":["Heroku"],"groups":[],"metadata":[{"name":"submissionViewable","value":"true"}],"startDate":"2020-06-29T12:09:00.000Z","terms":[{"roleId":"658d568e-0957-44ee-86bb-84105edb2b06","id":"82a35602-57c2-4b48-a9b9-b4e133b22035"},{"roleId":"16461876-297b-49a9-86cf-41b42f13ac97","id":"82a35602-57c2-4b48-a9b9-b4e133b22035"},{"roleId":"732339e7-8e30-49d7-9198-cccf9451e221","id":"b11da5cd-713f-478d-90f4-f679ef53ee95"},{"roleId":"89ebb5e3-fc58-4fac-85eb-af4c656cb87f","id":"82a35602-57c2-4b48-a9b9-b4e133b22035"},{"roleId":"b1df1a6e-81f7-46fc-b38d-eed46f54cde7","id":"82a35602-57c2-4b48-a9b9-b4e133b22035"},{"roleId":"cc25f311-89a9-43f5-85f9-3c56b6b71a3a","id":"75d2f6bb-aadc-475e-9728-32c1dbd13655"},{"roleId":"cfe12b3f-2a24-4639-9d8b-ec86726f76bd","id":"e0993b1a-abf7-45e6-8ed9-8cd0546be90b"}],"prizeSets":[{"prizes":[{"type":"USD","value":300}],"description":"Challenge Prizes","type":"placement"}],"legacy":{"reviewType":"community","track":"DESIGN"},"projectId":"16573","status":"Draft","attachmentIds":[]}' \
  --compressed
```
Following is the error in server logs:
```
15:26:16 (node:21) UnhandledPromiseRejectionWarning: ValidationError: Required value missing: id
15:26:16 at Attribute.toDynamo (/challenge-api/node_modules/dynamoose/dist/Attribute.js:365:19)
15:26:16 at Query.exec (/challenge-api/node_modules/dynamoose/dist/Query.js:94:47)
15:26:16 at Promise (/challenge-api/src/common/helper.js:194:42)
15:26:16 at Promise._execute (/challenge-api/node_modules/bluebird/js/release/debuggability.js:313:9)
15:26:16 at Promise._resolveFromExecutor (/challenge-api/node_modules/bluebird/js/release/promise.js:488:18)
15:26:16 at new Promise (/challenge-api/node_modules/bluebird/js/release/promise.js:79:10)
15:26:16 at Object.getById (/challenge-api/src/common/helper.js:193:10)
15:26:16 at populatePhases (/challenge-api/src/services/ChallengeService.js:390:33)
15:26:16 at update (/challenge-api/src/services/ChallengeService.js:905:11)
15:26:16 (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

**Comment by vikasrohit** [comment]
fyi @ThomasKranitsas @rootelement

**Comment by ThomasKranitsas** [comment]
PR: https://github.com/topcoder-platform/challenge-api/pull/206
cc @rootelement

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30132017 has been created for this ticket.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment]
Contest https://www.topcoder.com/challenges/30132017 has been updated - it has been assigned to thomaskranitsas.<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```

**Comment by ThomasKranitsas** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30132017<br/><br/>```This is an automated message for thomaskranitsas via Topcoder X```
