### ISSUE TITLE
[$40] Calls to the project API fail and API gets stuck

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/challenge-api#295]
from @vikasrohit on slack:

challenge api seems to non responsive for certain calls and I found following in logs (it seems if v3 direct api is down, v5 also fails):
```
{ url: 'https://api.topcoder-dev.com/v3/direct/projects/23570',
...
t] },
17:15:12 data:
17:15:12 '<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n' },
17:15:12 isAxiosError: true,
17:15:12 toJSON: [Function] }
17:15:12 [31merror[39m: Error: Request failed with status code 504
17:15:12 at createError (/challenge-api/node_modules/axios/lib/core/createError.js:16:15)
17:15:12 at settle (/challenge-api/node_modules/axios/lib/core/settle.js:17:12)
17:15:12 at IncomingMessage.handleStreamEnd (/challenge-api/node_modules/axios/lib/adapters/http.js:237:11)
17:15:12 at IncomingMessage.emit (events.js:203:15)
17:15:12 at IncomingMessage.EventEmitter.emit (domain.js:448:20)
17:15:12 at endReadableNT (_stream_readable.js:1145:12)
17:15:12 at process._tickCallback (internal/process/next_tick.js:63:19)
```
Not sure if that is already known thing, just wanted to raise in case we missed something here. I was expecting all v3/v4 api calls are now in processors.

cc @rootelement

**Comment by ThomasKranitsas** [comment]
Fixed in https://github.com/topcoder-platform/challenge-api/commit/8bf485f5169560bfc64eacd0cf0a65bf097224d7

**Comment by rootelement** [comment]
Contest https://www.topcoder.com/challenges/30145101 has been created for this ticket.<br/><br/>```This is an automated message for jcori via Topcoder X```

**Comment by rootelement** [comment]
Contest https://www.topcoder.com/challenges/30145101 has been updated - it has been assigned to thomaskranitsas.<br/><br/>```This is an automated message for jcori via Topcoder X```

**Comment by rootelement** [comment]
Payment task has been updated: https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30145101<br/><br/>```This is an automated message for jcori via Topcoder X```
