### ISSUE TITLE
Activate Challenge - Internal Reviewer Error

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/challenge-api#317]
Right now if you Activate a challenge with an internal reviewer selected, you get an error from Direct. I believe it's because the challenge resource for the internal reviewer is either not created in legacy yet, or it's not attached to the phase somehow? Or the reviewer selected doesn't have the correct role to be a reviewer? Not sure

## Error from Direct
![image](https://user-images.githubusercontent.com/5400156/94944508-5bbb8e80-04a7-11eb-90b8-10a0f2818951.png)

## Legacy Challenge Processor Errors
(won't let me word-wrap it, so the logs are a bit weird to look at. Might be cleanest to copy/paste them into an editor)
```
[32minfo[39m: Handle Kafka event message; Topic: challenge.notification.update; Partition: 3; Offset: 18141; Message: {"topic":"challenge.notification.update","originator":"topcoder-challenges-api","timestamp":"2020-10-02T14:41:42.484Z","mime-type":"application/json","payload":{"projectId":"16640","terms":[{"id":"82a35602-57c2-4b48-a9b9-b4e133b22035","roleId":"3eedd4a4-3c68-4f68-8de4-a1ca5c2055e5"},{"id":"82a35602-57c2-4b48-a9b9-b4e133b22035","roleId":"318b9c07-079a-42d9-a81f-b96be1dc1099"},{"id":"b11da5cd-713f-478d-90f4-f679ef53ee95","roleId":"732339e7-8e30-49d7-9198-cccf9451e221"},{"id":"82a35602-57c2-4b48-a9b9-b4e133b22035","roleId":"ff556573-5da6-4392-b38c-08c1d7599c4a"},{"id":"82a35602-57c2-4b48-a9b9-b4e133b22035","roleId":"d663fc84-5c37-43d1-a537-793feffb7667"},{"id":"82a35602-57c2-4b48-a9b9-b4e133b22035","roleId":"e0544b94-6420-4afc-8f63-238eddc751b9"},{"id":"75d2f6bb-aadc-475e-9728-32c1dbd13655","roleId":"0e9c6879-39e4-4eb6-b8df-92407890faf1"},{"id":"e0993b1a-abf7-45e6-8ed9-8cd0546be90b","roleId":"cfe12b3f-2a24-4639-9d8b-ec86726f76bd"}],"task":{"isTask":false,"isAssigned":false,"memberId":null},"typeId":"927abff4-7af9-4145-8ba1-577c16e64e2e","legacyId":30057224,"endDate":"2020-10-13T02:35:22.000Z","status":"Active","trackId":"9b6fc876-f4d9-4ccb-9dfd-419247628825","created":"2020-10-02T14:35:57.000Z","updatedBy":"jcori","createdBy":"tcwebservice","name":"Test with New BA 1","timelineTemplateId":"7ebf1c69-f62f-4d3a-bdfb-fe9ddb56861c","groups":["b8fe66cc-935f-4986-a1cf-5e1dee943e8a"],"descriptionFormat":"HTML","updated":"2020-10-02T14:41:42.402Z","phases":[{"id":"af96fdde-e89d-4c4c-b52a-b0d0693684f4","phaseId":"a93544bc-c165-4af4-b55e-18f3593b457a","duration":259200,"scheduledStartDate":"2020-10-03T14:35:22Z","scheduledEndDate":"2020-10-06T14:35:22.000Z","actualStartDate":"2020-10-03T14:35:22Z","actualEndDate":"2020-10-06T14:35:22.000Z","isOpen":false},{"id":"a9653463-cee0-4b0b-8a94-f586ee0af598","phaseId":"6950164f-3c5e-4bdc-abc8-22aaf5a1bd49","duration":259200,"scheduledStartDate":"2020-10-06T14:35:22.000Z","scheduledEndDate":"2020-10-09T14:35:22.000Z","actualStartDate":"2020-10-06T14:35:22.000Z","actualEndDate":"2020-10-09T14:35:22.000Z","isOpen":false,"predecessor":"af96fdde-e89d-4c4c-b52a-b0d0693684f4"},{"id":"3e27f7aa-1c71-46bb-b09f-defe23058de2","phaseId":"aa5a3f78-79e0-4bf7-93ff-b11e8f5b398b","duration":172800,"scheduledStartDate":"2020-10-09T14:35:22.000Z","scheduledEndDate":"2020-10-11T14:35:22.000Z","actualStartDate":"2020-10-09T14:35:22.000Z","actualEndDate":"2020-10-11T14:35:22.000Z","isOpen":false,"predecessor":"a9653463-cee0-4b0b-8a94-f586ee0af598"},{"id":"c8aa9951-bf7d-453f-970a-8898910b4f6e","phaseId":"1c24cfb3-5b0a-4dbd-b6bd-4b0dff5349c6","duration":86400,"scheduledStartDate":"2020-10-11T14:35:22.000Z","scheduledEndDate":"2020-10-12T14:35:22.000Z","actualStartDate":"2020-10-11T14:35:22.000Z","actualEndDate":"2020-10-12T14:35:22.000Z","isOpen":false,"predecessor":"3e27f7aa-1c71-46bb-b09f-defe23058de2"},{"id":"3f4c7923-db98-4a4f-b291-80c67029deb1","phaseId":"797a6af7-cd3f-4436-9fca-9679f773bee9","duration":43200,"scheduledStartDate":"2020-10-12T14:35:22.000Z","scheduledEndDate":"2020-10-13T02:35:22.000Z","actualStartDate":"2020-10-12T14:35:22.000Z","actualEndDate":"2020-10-13T02:35:22.000Z","isOpen":false,"predecessor":"c8aa9951-bf7d-453f-970a-8898910b4f6e"}],"prizeSets":[{"type":"placement","description":"Challenge Prizes","prizes":[{"type":"USD","value":1000},{"type":"USD","value":500}]},{"type":"copilot","prizes":[{"type":"copilot","value":12}]}],"startDate":"2020-10-03T14:35:22Z","legacy":{"track":"DEVELOP","subTrack":"CODE","reviewType":"INTERNAL","forumId":0,"directProjectId":23678,"reviewScorecardId":30001610,"isTask":false},"description":"## Ursaeque suum\n\nFacti placabat, mox cumque est saepe cum visus; hic nomine sinuantur! Pedes\nnamque quibus, per versus negant ait tuque alta spes exegit, aeternus taurum\npectora comitum, at recludit.\n\n## Auctore ubi ramos contigit Tyros intellegit matris\n\nEventu Siphnon viridis mortalia tantis destrinxit vulnifico tuta evitabile\ndulci! Tauri in et, si fulva ut dura satis amentes Brotean, tota contraria\ninmunesque orbe patremque telum.\n\n1. Mora per enim flammas nec mora\n2. Saecula capiti dicta\n3. Bicolor nec cura miles\n4. Clementia promissa\n5. Sine antiqua hosti Antimachumque offer at risisse\n\n## Tenvit capillos vertatur breve Lucifer defecisse virum\n\nTerrarum Idmoniae vicimus peteret promissi: una et umerosque summus vidisse\nbracchia per alto. Lympha cruciataque cunctis nescit. Fama divino a parte\ncorpore vetat. Non cum hinc formatus claro, nato **non illic levabere** sustinet\nastris hosne intus hoc dei fui, inde multa. Successu linguae hic regia vicem\nquoque exercent animosque nescius, quisque gerit caesariem.\n\nPugnat miserisque mensis copia! Lucis iura, mille suis; matrem eurus unde\nsubiere latrasse; te ipsa sanguine! Et redit etiam generosior capistris alterius\nvestrae leges! Tamen in modo, nymphas eo ut accedere *sacras* concilio illis:\ninvecta [quam partem profugos](http://www.aeneas.com/); veluti. In utinam angue\n*omnia elabique credunt* inque mihi quid nefas\n[vigilat](http://www.liceretilla.net/deorum-thalamosque).","id":"7e50485c-2793-43a0-8437-de81834de961","tags":["AWS"],"metadata":[],"attachments":[],"track":"Development","type":"Challenge","billingAccountId":80000639}}.
2020-10-02T10:41:43.922-04:00	[32minfo[39m: GroupIDs Found in Informix: ["20000010"]
2020-10-02T10:41:44.698-04:00	[31merror[39m: processUpdate Catch Bad Request {"status":400,"response":{"req":{"method":"PUT","url":"https://api.topcoder-dev.com/v4/challenges/30057224","data":{"param":{"track":"DEVELOP","subTrack":"CODE","name":"Test with New BA 1","reviewType":"INTERNAL","projectId":23678,"status":"Active","billingAccountId":80000639,"detailedRequirements":"## Ursaeque suum\n\nFacti placabat, mox cumque est saepe cum visus; hic nomine sinuantur! Pedes\nnamque quibus, per versus negant ait tuque alta spes exegit, aeternus taurum\npectora comitum, at recludit.\n\n## Auctore ubi ramos contigit Tyros intellegit matris\n\nEventu Siphnon viridis mortalia tantis destrinxit vulnifico tuta evitabile\ndulci! Tauri in et, si fulva ut dura satis amentes Brotean, tota contraria\ninmunesque orbe patremque telum.\n\n1. Mora per enim flammas nec mora\n2. Saecula capiti dicta\n3. Bicolor nec cura miles\n4. Clementia promissa\n5. Sine antiqua hosti Antimachumque offer at risisse\n\n## Tenvit capillos vertatur breve Lucifer defecisse virum\n\nTerrarum Idmoniae vicimus peteret promissi: una et umerosque summus vidisse\nbracchia per alto. Lympha cruciataque cunctis nescit. Fama divino a parte\ncorpore vetat. Non cum hinc formatus claro, nato **non illic levabere** sustinet\nastris hosne intus hoc dei fui, inde multa. Successu linguae hic regia vicem\nquoque exercent animosque nescius, quisque gerit caesariem.\n\nPugnat miserisque mensis copia! Lucis iura, mille suis; matrem eurus unde\nsubiere latrasse; te ipsa sanguine! Et redit etiam generosior capistris alterius\nvestrae leges! Tamen in modo, nymphas eo ut accedere *sacras* concilio illis:\ninvecta [quam partem profugos](http://www.aeneas.com/); veluti. In utinam angue\n*omnia elabique credunt* inque mihi quid nefas\n[vigilat](http://www.liceretilla.net/deorum-thalamosque).","registrationStartsAt":"2020-10-03T14:35:22.000Z","registrationEndsAt":"2020-10-06T14:35:22.000Z","registrationDuration":259200000,"submissionEndsAt":"2020-10-06T14:35:22.000Z","submissionDuration":259200000,"checkpointSubmissionStartsAt":null,"checkpointSubmissionEndsAt":null,"checkpointSubmissionDuration":null,"numberOfCheckpointPrizes":0,"checkpointPrize":0,"prizes":[1000,500],"technologies":[],"platforms":[{"name":"AWS","id":4}]}},"headers":{"content-type":"application/json","authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5VSkZORGd4UlRVME5EWTBOVVkzTlRkR05qTXlRamxETmpOQk5UYzVRVUV3UlRFeU56TTJRUSJ9.eyJpc3MiOiJodHRwczovL3RvcGNvZGVyLWRldi5hdXRoMC5jb20vIiwic3ViIjoiakdJZjJwZDNmNDRCMWpxdk9haTMwQklLVFphbllCZlVAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vbTJtLnRvcGNvZGVyLWRldi5jb20vIiwiaWF0IjoxNjAxNTcwNjQxLCJleHAiOjE2MDE2NTcwNDEsImF6cCI6ImpHSWYycGQzZjQ0QjFqcXZPYWkzMEJJS1RaYW5ZQmZVIiwic2NvcGUiOiJ1cGRhdGU6dXNlcl9wcm9maWxlcyB3cml0ZTp1c2VyX3Byb2ZpbGVzIGNyZWF0ZTpjb25uZWN0X3Byb2plY3QgYWxsOmNoYWxsZW5nZXMgcmVhZDpjaGFsbGVuZ2VzIHdyaXRlOmNoYWxsZW5nZXMgYWxsOmdyb3VwcyB3cml0ZTpncm91cHMgcmVhZDpncm91cHMgdXBkYXRlOnN1Ym1pc3Npb24gcmVhZDpzdWJtaXNzaW9uIGRlbGV0ZTpzdWJtaXNzaW9uIGNyZWF0ZTpzdWJtaXNzaW9uIGFsbDpzdWJtaXNzaW9uIHJlYWQ6cHJvamVjdCBhbGw6Y29ubmVjdF9wcm9qZWN0IHJlYWQ6YnVzX3RvcGljcyB3cml0ZTpidXNfYXBpIHJlYWQ6ZW1haWxfdGVtcGxhdGVzIHJlYWQ6dXNlcl9wcm9maWxlcyByZWFkOnJvbGVzIHJlYWQ6cHJvamVjdC11c2VyIHJlYWQ6cHJvamVjdC1wZXJtaXNzaW9uIHJlYWQ6cmVzb3VyY2VzIHdyaXRlOnJlc291cmNlcyBkZWxldGU6cmVzb3VyY2VzIHVwZGF0ZTpyZXNvdXJjZXMgYWxsOnJlc291cmNlcyByZWFkOnRlcm1zIGFsbDp0ZXJtcyBhbGw6cHJvamVjdHMgcmVhZDpwcm9qZWN0cyIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.n8R2N9FCAqnRT5L8uVEEM_TMep60QpkDvhx9mcgyqsBC1L2xy33sqzUcvNhn3L2rB74tAyJ0Zh3jqOHidbQ77rQIdVjCkNP74KIrgerkixrcvHttjzfZTNH3Lm5OpZWZfvOFpUvZfuvqKBnJSz-LTtE8QMnsHmysjsSdArcCdTkw_exFKW7gFsEVpOV1J_JoCRQXNse0jnTnNcjIrFnTjllEW42SwjR_mxpueYuiwEd7f4k82gnyMudwOoF_O3SWxXhEYleL9TWWD-J9ljaC7inKwf3KWtKUbVetXooWW2szQpDxco8i8XGinXRCwi0f_HLNlgJYopzhRs-DP4-g8A","accept":"application/json"}},"header":{"date":"Fri, 02 Oct 2020 14:41:44 GMT","content-type":"application/json","content-length":"161","connection":"close","server":"nginx","access-control-allow-headers":"Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, OPTIONS, DELETE, PUT, PATCH"},"status":400,"text":"{\"id\":\"-30457dc9:174d4d8525a:5489\",\"result\":{\"success\":true,\"status\":400,\"metadata\":null,\"content\":\"javax.ejb.EJBTransactionRolledbackException\"},\"version\":\"v3\"}"},"stack":"Error: Bad Request\n at Request.callback (/app/node_modules/superagent/lib/node/index.js:883:15)\n at /app/node_modules/superagent/lib/node/index.js:1127:20\n at IncomingMessage.<anonymous> (/app/node_modules/superagent/lib/node/parsers/json.js:22:7)\n at IncomingMessage.emit (events.js:194:15)\n at endReadableNT (_stream_readable.js:1103:12)\n at process._tickCallback (internal/process/next_tick.js:63:19)"}
2020-10-02T10:41:44.698-04:00	[31merror[39m: { Error: Bad Request
2020-10-02T10:41:44.698-04:00	at Request.callback (/app/node_modules/superagent/lib/node/index.js:883:15)
2020-10-02T10:41:44.698-04:00	at /app/node_modules/superagent/lib/node/index.js:1127:20
2020-10-02T10:41:44.698-04:00	at IncomingMessage.<anonymous> (/app/node_modules/superagent/lib/node/parsers/json.js:22:7)
2020-10-02T10:41:44.698-04:00	at IncomingMessage.emit (events.js:194:15)
2020-10-02T10:41:44.698-04:00	at endReadableNT (_stream_readable.js:1103:12)
2020-10-02T10:41:44.698-04:00	at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by rootelement** [comment]
@ajefts Can you weigh in on what prereqs an internal reviewer must meet?

**Comment by ajefts** [comment]
@rootelement Take a look at https://github.com/appirio-tech/direct-app/blob/221d3ebbed0c8d7892cfb40291d6ca138c30add1/components/online_review_upload_services/src/java/main/com/cronos/onlinereview/services/uploads/impl/DefaultUploadServices.java#L1398.  I think we're probably missing a couple properties that need to be set on the resource record.

**Comment by vikasrohit** [comment]
@rootelement to confirm, WM is adding the reviewer as `Reviewer` resource (318b9c07-079a-42d9-a81f-b96be1dc1099) using v5 api when user sets internal reviewer.
<img width="699" alt="Screen Shot 2020-10-06 at 2 44 05 PM" src="https://user-images.githubusercontent.com/2417632/95182536-64330280-07e2-11eb-8def-ab434d0be320.png">

**Comment by rootelement** [comment]
@ThomasKranitsas looks like this is missing:
https://github.com/appirio-tech/direct-app/blob/221d3ebbed0c8d7892cfb40291d6ca138c30add1/components/online_review_upload_services/src/java/main/com/cronos/onlinereview/services/uploads/impl/DefaultUploadServices.java#L1467

**Comment by rootelement** [comment]
I've confirmed. I created a challenge in direct with an internal reviewer. This is what the resources look like for that challenge in informix:
<img width="948" alt="Screen Shot 2020-10-06 at 9 55 56 AM" src="https://user-images.githubusercontent.com/5400156/95211109-29b56f80-07ba-11eb-8421-847e8c524971.png">
And this is what the resource_info for that last resource looks like:
<img width="881" alt="Screen Shot 2020-10-06 at 9 56 03 AM" src="https://user-images.githubusercontent.com/5400156/95211143-33d76e00-07ba-11eb-9229-afc4d5b63eda.png">

So we have the resource_info correct, but we need to populate the `project_phase_id` for the internal reviewer.

**Comment by rootelement** [comment]
Committing a fix attempt now. Will test.

**Comment by rootelement** [comment]
Success!
https://challenges.topcoder-dev.com/projects/16640/challenges/d534ab7d-7ae5-4328-8aad-e3b05d6b4751/view

<img width="957" alt="Screen Shot 2020-10-06 at 11 58 14 AM" src="https://user-images.githubusercontent.com/5400156/95226703-4312e780-07cb-11eb-8693-a76d28430de4.png">

**Comment by rootelement** [comment]
Fixed in prod
