### ISSUE TITLE
Challenge Forum Title Limit

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/challenge-api#387]
Member created a challenge and the challenge title was too long for the challenge forum processor. We need to limit/truncate this somewhere. Will decide where.

## Logs from Challenge Forum Processor
```
2021-02-22T07:55:06.482-05:00Copy[33m2021-02-22T12:55:06.482Z[39m [[34mdebug[39m]: Message from challenge.notification.create: [{     "id": "bed5ead7-1358-4dae-a78b-a8c7a9d2f82a",     "created": "2021-02-22T12:55:05.389Z",     "createdBy": "billsedison",     "updated": "2021-02-22T12:55:05.389Z",     "updatedBy": "billsedison",     "status": "New",     "projectId": 24260,     "name": "Adobe Challenge Series - Week 2/6 - Get started with Adobe PDF API and Adobe Sign API (Weekly Prizes)",     "typeId": "927abff4-7af9-4145-8ba1-577c16e64e2e",     "trackId": "9b6fc876-f4d9-4ccb-9dfd-419247628825",     "startDate": "2021-02-23T12:55:04.000Z",     "legacy": {         "reviewType": "COMMUNITY"     },     "descriptionFormat": "markdown",     "timelineTemplateId": "7ebf1c69-f62f-4d3a-bdfb-fe9ddb56861c",     "terms": [         {             "id": "564a981e-6840-4a5c-894e-d5ad22e9cd6f",             "roleId": "732339e7-8e30-49d7-9198-cccf9451e221"         }     ],     "groups": [],     "discussions": [         {             "name": "Adobe Challenge Series - Week 2/6 - Get started with Adobe PDF API and Adobe Sign API (Weekly Prizes) Discussion",             "type": "challenge",             "provider": "vanilla",             "id": "7adea101-2223-4a06-b92f-7453dcd9b13b"         }     ],     "description": "",     "phases": [         {             "phaseId": "a93544bc-c165-4af4-b55e-18f3593b457a",             "duration": 432000,             "id": "fe40c4c0-dea8-4990-8365-e7e572095bcc",             "name": "Registration",             "isOpen": false,             "scheduledStartDate": "2021-02-23T20:55:04+08:00",             "scheduledEndDate": "2021-02-28T12:55:04.000Z",             "actualStartDate": "2021-02-23T20:55:04+08:00",             "actualEndDate": "2021-02-28T12:55:04.000Z"         },         {             "phaseId": "6950164f-3c5e-4bdc-abc8-22aaf5a1bd49",             "duration": 432000,             "id": "1d4afede-2110-461e-b266-bcebbf7e4d94",             "name": "Submission",             "isOpen": false,             "scheduledStartDate": "2021-02-23T20:55:04+08:00",             "scheduledEndDate": "2021-02-28T12:55:04.000Z",             "actualStartDate": "2021-02-23T20:55:04+08:00",             "actualEndDate": "2021-02-28T12:55:04.000Z"         },         {             "phaseId": "aa5a3f78-79e0-4bf7-93ff-b11e8f5b398b",             "duration": 172800,             "id": "2c3475c3-0008-4285-ae11-3a4a1a884584",             "name": "Review",             "isOpen": false,             "predecessor": "1d4afede-2110-461e-b266-bcebbf7e4d94",             "scheduledStartDate": "2021-02-28T12:55:04.000Z",             "scheduledEndDate": "2021-03-02T12:55:04.000Z",             "actualStartDate": "2021-02-28T12:55:04.000Z",             "actualEndDate": "2021-03-02T12:55:04.000Z"         },         {             "phaseId": "1c24cfb3-5b0a-4dbd-b6bd-4b0dff5349c6",             "duration": 43200,             "id": "e90e6874-1d33-4ee6-83a4-9d6ff0fe6340",             "name": "Appeals",             "isOpen": false,             "predecessor": "2c3475c3-0008-4285-ae11-3a4a1a884584",             "scheduledStartDate": "2021-03-02T12:55:04.000Z",             "scheduledEndDate": "2021-03-03T00:55:04.000Z",             "actualStartDate": "2021-03-02T12:55:04.000Z",             "actualEndDate": "2021-03-03T00:55:04.000Z"         },         {             "phaseId": "797a6af7-cd3f-4436-9fca-9679f773bee9",             "duration": 57600,             "id": "04d40e4e-34c6-48b5-b5a8-47ff46f68675",             "name": "Appeals Response",             "isOpen": false,             "predecessor": "e90e6874-1d33-4ee6-83a4-9d6ff0fe6340",             "scheduledStartDate": "2021-03-03T00:55:04.000Z",             "scheduledEndDate": "2021-03-03T16:55:04.000Z",             "actualStartDate": "2021-03-03T00:55:04.000Z",             "actualEndDate": "2021-03-03T16:55:04.000Z"         }     ],     "endDate": "2021-03-03T16:55:04.000Z",     "numOfSubmissions": 0,     "numOfRegistrants": 0,     "currentPhaseNames": [],     "registrationStartDate": "2021-02-23T20:55:04+08:00",     "registrationEndDate": "2021-02-28T12:55:04.000Z",     "submissionStartDate": "2021-02-23T20:55:04+08:00",     "submissionEndDate": "2021-02-28T12:55:04.000Z",     "track": "Development",     "type": "Challenge" }] | [33m2021-02-22T12:55:06.482Z[39m [[34mdebug[39m]: Message from challenge.notification.create: [{"id":"bed5ead7-1358-4dae-a78b-a8c7a9d2f82a","created":"2021-02-22T12:55:05.389Z","createdBy":"billsedison","updated":"2021-02-22T12:55:05.389Z","updatedBy":"billsedison","status":"New","projectId":24260,"name":"Adobe Challenge Series - Week 2/6 - Get started with Adobe PDF API and Adobe Sign API (Weekly Prizes)","typeId":"927abff4-7af9-4145-8ba1-577c16e64e2e","trackId":"9b6fc876-f4d9-4ccb-9dfd-419247628825","startDate":"2021-02-23T12:55:04.000Z","legacy":{"reviewType":"COMMUNITY"},"descriptionFormat":"markdown","timelineTemplateId":"7ebf1c69-f62f-4d3a-bdfb-fe9ddb56861c","terms":[{"id":"564a981e-6840-4a5c-894e-d5ad22e9cd6f","roleId":"732339e7-8e30-49d7-9198-cccf9451e221"}],"groups":[],"discussions":[{"name":"Adobe Challenge Series - Week 2/6 - Get started with Adobe PDF API and Adobe Sign API (Weekly Prizes) Discussion","type":"challenge","provider":"vanilla","id":"7adea101-2223-4a06-b92f-7453dcd9b13b"}],"description":"","phases":[{"phaseId":"a93544bc-c165-4af4-b55e-18f3593b457a","duration":432000,"id":"fe40c4c0-dea8-4990-8365-e7e572095bcc","name":"Registration","isOpen":false,"scheduledStartDate":"2021-02-23T20:55:04+08:00","scheduledEndDate":"2021-02-28T12:55:04.000Z","actualStartDate":"2021-02-23T20:55:04+08:00","actualEndDate":"2021-02-28T12:55:04.000Z"},{"phaseId":"6950164f-3c5e-4bdc-abc8-22aaf5a1bd49","duration":432000,"id":"1d4afede-2110-461e-b266-bcebbf7e4d94","name":"Submission","isOpen":false,"scheduledStartDate":"2021-02-23T20:55:04+08:00","scheduledEndDate":"2021-02-28T12:55:04.000Z","actualStartDate":"2021-02-23T20:55:04+08:00","actualEndDate":"2021-02-28T12:55:04.000Z"},{"phaseId":"aa5a3f78-79e0-4bf7-93ff-b11e8f5b398b","duration":172800,"id":"2c3475c3-0008-4285-ae11-3a4a1a884584","name":"Review","isOpen":false,"predecessor":"1d4afede-2110-461e-b266-bcebbf7e4d94","scheduledStartDate":"2021-02-28T12:55:04.000Z","scheduledEndDate":"2021-03-02T12:55:04.000Z","actualStartDate":"2021-02-28T12:55:04.000Z","actualEndDate":"2021-03-02T12:55:04.000Z"},{"phaseId":"1c24cfb3-5b0a-4dbd-b6bd-4b0dff5349c6","duration":43200,"id":"e90e6874-1d33-4ee6-83a4-9d6ff0fe6340","name":"Appeals","isOpen":false,"predecessor":"2c3475c3-0008-4285-ae11-3a4a1a884584","scheduledStartDate":"2021-03-02T12:55:04.000Z","scheduledEndDate":"2021-03-03T00:55:04.000Z","actualStartDate":"2021-03-02T12:55:04.000Z","actualEndDate":"2021-03-03T00:55:04.000Z"},{"phaseId":"797a6af7-cd3f-4436-9fca-9679f773bee9","duration":57600,"id":"04d40e4e-34c6-48b5-b5a8-47ff46f68675","name":"Appeals Response","isOpen":false,"predecessor":"e90e6874-1d33-4ee6-83a4-9d6ff0fe6340","scheduledStartDate":"2021-03-03T00:55:04.000Z","scheduledEndDate":"2021-03-03T16:55:04.000Z","actualStartDate":"2021-03-03T00:55:04.000Z","actualEndDate":"2021-03-03T16:55:04.000Z"}],"endDate":"2021-03-03T16:55:04.000Z","numOfSubmissions":0,"numOfRegistrants":0,"currentPhaseNames":[],"registrationStartDate":"2021-02-23T20:55:04+08:00","registrationEndDate":"2021-02-28T12:55:04.000Z","submissionStartDate":"2021-02-23T20:55:04+08:00","submissionEndDate":"2021-02-28T12:55:04.000Z","track":"Development","type":"Challenge"}]
-- | --
  | 2021-02-22T07:55:06.483-05:00 | [33m2021-02-22T12:55:06.483Z[39m [[32minfo[39m]: The challenge with challengeID=bed5ead7-1358-4dae-a78b-a8c7a9d2f82a:
  | 2021-02-22T07:55:06.609-05:00 | [33m2021-02-22T12:55:06.609Z[39m [[32minfo[39m]: Managing user for challengeID=bed5ead7-1358-4dae-a78b-a8c7a9d2f82a [action=invite, handle=billsedison, projectRole=null, challengeRoles=["Manager"]]...
  | 2021-02-22T07:55:06.760-05:00 | [33m2021-02-22T12:55:06.760Z[39m [[32minfo[39m]: Creating Vanilla entities for the 'Adobe Challenge Series - Week 2/6 - Get started with Adobe PDF API and Adobe Sign API (Weekly Prizes) Discussion' discussion ....
  | 2021-02-22T07:55:06.762-05:00 | [33m2021-02-22T12:55:06.762Z[39m [[31merror[39m]: Error: The group wasn't not found by challengeID
  | 2021-02-22T07:55:06.762-05:00 | at manageVanillaUser (/challenge-forum-processor/src/services/vanilla.js:28:11)
  | 2021-02-22T07:55:06.762-05:00 | at <anonymous>
  | 2021-02-22T07:55:06.762-05:00 | at process._tickCallback (internal/process/next_tick.js:189:7)
  | 2021-02-22T07:55:06.888-05:00 | [33m2021-02-22T12:55:06.888Z[39m [[31merror[39m]: { Error: Bad Request
  | 2021-02-22T07:55:06.888-05:00 | at Request.callback (/challenge-forum-processor/node_modules/superagent/lib/node/index.js:871:15)
  | 2021-02-22T07:55:06.888-05:00 | at /challenge-forum-processor/node_modules/superagent/lib/node/index.js:1114:20
  | 2021-02-22T07:55:06.888-05:00 | at IncomingMessage.<anonymous> (/challenge-forum-processor/node_modules/superagent/lib/node/parsers/json.js:22:7)
  | 2021-02-22T07:55:06.888-05:00 | at emitNone (events.js:111:20)
  | 2021-02-22T07:55:06.888-05:00 | at IncomingMessage.emit (events.js:208:7)
  | 2021-02-22T07:55:06.888-05:00 | at endReadableNT (_stream_readable.js:1064:12)
  | 2021-02-22T07:55:06.888-05:00 | at _combinedTickCallback (internal/process/next_tick.js:139:11)
  | 2021-02-22T07:55:06.888-05:00 | at process._tickCallback (internal/process/next_tick.js:181:9)
  | 2021-02-22T07:55:06.888-05:00 | status: 400,
  | 2021-02-22T07:55:06.888-05:00 | response:
  | 2021-02-22T07:55:06.888-05:00 | Response {
  | 2021-02-22T07:55:06.888-05:00 | domain: null,
  | 2021-02-22T07:55:06.888-05:00 | _events: {},
  | 2021-02-22T07:55:06.888-05:00 | _eventsCount: 0,
  | 2021-02-22T07:55:06.888-05:00 | _maxListeners: undefined,
  | 2021-02-22T07:55:06.888-05:00 | res:
  | 2021-02-22T07:55:06.888-05:00 | IncomingMessage {
  | 2021-02-22T07:55:06.888-05:00 | _readableState: [Object],
  | 2021-02-22T07:55:06.888-05:00 | readable: false,
  | 2021-02-22T07:55:06.888-05:00 | domain: null,
  | 2021-02-22T07:55:06.888-05:00 | _events: [Object],
  | 2021-02-22T07:55:06.888-05:00 | _eventsCount: 4,
  | 2021-02-22T07:55:06.888-05:00 | _maxListeners: undefined,
  | 2021-02-22T07:55:06.888-05:00 | socket: [Object],
  | 2021-02-22T07:55:06.888-05:00 | connection: [Object],
  | 2021-02-22T07:55:06.888-05:00 | httpVersionMajor: 1,
  | 2021-02-22T07:55:06.888-05:00 | httpVersionMinor: 1,
  | 2021-02-22T07:55:06.888-05:00 | httpVersion: '1.1',
  | 2021-02-22T07:55:06.888-05:00 | complete: true,
  | 2021-02-22T07:55:06.888-05:00 | headers: [Object],
  | 2021-02-22T07:55:06.888-05:00 | rawHeaders: [Array],
  | 2021-02-22T07:55:06.888-05:00 | trailers: {},
  | 2021-02-22T07:55:06.888-05:00 | rawTrailers: [],
  | 2021-02-22T07:55:06.888-05:00 | upgrade: false,
  | 2021-02-22T07:55:06.888-05:00 | url: '',
  | 2021-02-22T07:55:06.888-05:00 | method: null,
  | 2021-02-22T07:55:06.888-05:00 | statusCode: 400,
  | 2021-02-22T07:55:06.888-05:00 | statusMessage: 'Bad Request',
  | 2021-02-22T07:55:06.888-05:00 | client: [Object],
  | 2021-02-22T07:55:06.888-05:00 | _consuming: true,
  | 2021-02-22T07:55:06.888-05:00 | _dumped: false,
  | 2021-02-22T07:55:06.888-05:00 | req: [Object],
  | 2021-02-22T07:55:06.888-05:00 | text: '{\n "message": "Validation Failed",\n "status": 400,\n "errors": [\n {\n "field": "name",\n "code": "Name is 1 characters too long.",\n "status": 400,\n "message": "Name is 1 characters too long."\n }\n ]\n}',
...
```

**Comment by rootelement** [comment]
@vikasrohit @ThomasKranitsas @jmgasper 
This is a problem we have to solve across the three properties, WM, Challenge API, Forum Processor:

1. @jmgasper - Please confirm the Challenge Forum Title character limit. We will also need to retry creating a forum on `challenge.notifications.update` if the same conditions exist - discussions object exists with no url. Right now i have no way to recreate a forum if it fails.
2. @vikasrohit - We need to limit Challenge Title length anyway. I don't know if we 100% want to limit challenge title, or we want to truncate forum title, or if we want to give them the option to name the forum separately in WM

**Comment by ThomasKranitsas** [comment]
PR https://github.com/topcoder-platform/challenge-api/pull/395
